### ISSUE TITLE
Install error in Mac OSX

### ISSUE THREAD

**Issue by robotnc** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#1]
Hi, I try to install it in Mac OSX but failed. Is it possible to install it in Mac ?

Mac:World robot$ python setup.py install
running install
running bdist_egg
running egg_info
writing pyworld.egg-info/PKG-INFO
writing top-level names to pyworld.egg-info/top_level.txt
writing dependency_links to pyworld.egg-info/dependency_links.txt
reading manifest file 'pyworld.egg-info/SOURCES.txt'
writing manifest file 'pyworld.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-x86_64/egg
running install_lib
running build_ext
skipping 'pyworld.cpp' Cython extension (up-to-date)
building 'pyworld' extension
gcc -fno-strict-aliasing -I//anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I//anaconda/lib/python2.7/site-packages/numpy/core/include -I/Users/robot/work/vocoder/World/src -I//anaconda/include/python2.7 -c pyworld.cpp -o build/temp.macosx-10.5-x86_64-2.7/pyworld.o
In file included from pyworld.cpp:252:
In file included from //anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from //anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
In file included from //anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1781:
//anaconda/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "
      "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
pyworld.cpp:1407:9: warning: conversion from string literal to 'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
        PyErr_BadInternalCall();
        ^
//anaconda/include/python2.7/pyerrors.h:221:56: note: expanded from macro 'PyErr_BadInternalCall'
#define PyErr_BadInternalCall() _PyErr_BadInternalCall(__FILE__, __LINE__)
                                                       ^
<scratch space>:114:1: note: expanded from here
"pyworld.cpp"
^
pyworld.cpp:3307:3: error: no matching function for call to 'InitializeCheapTrickOption'
  InitializeCheapTrickOption((&__pyx_v_option));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
./src/world/cheaptrick.h:51:6: note: candidate function not viable: requires 2 arguments, but 1 was provided
void InitializeCheapTrickOption(int fs, CheapTrickOption *option);
     ^
pyworld.cpp:3811:3: error: no matching function for call to 'InitializeCheapTrickOption'
  InitializeCheapTrickOption((&__pyx_v_opt));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
./src/world/cheaptrick.h:51:6: note: candidate function not viable: requires 2 arguments, but 1 was provided
void InitializeCheapTrickOption(int fs, CheapTrickOption *option);
     ^
2 warnings and 2 errors generated.
error: command 'gcc' failed with exit status 1

**Comment by robotnc** [comment]
The reason is World source code upgrade. add fs to function InitializeCheapTrickOption(int fs, CheapTrickOption *option); can solve this.

**Comment by ajinkyakulkarni14** [comment]
How this issue is solved ?

**Comment by Soar-Sir** [comment]
I also meet this issus, so How this issue is solved?

**Comment by JeremyCCHsu** [comment]
Do you mind trying to install it from source? (6 lines of commands)
https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder#installing-from-github

I don't have a Mac and cannot reproduce the error you reported.

**Comment by keunwoochoi** [comment]
I tried and had the same error on my Mac, 10.14.6 Mojave.
```bash
$ pip install .
Processing /Users/keunwooc/Repos/Python-Wrapper-for-World-Vocoder
Requirement already satisfied: numpy in /Users/keunwooc/opt/miniconda3/envs/dcunettorch/lib/python3.7/site-packages (from pyworld==0.2.8) (1.15.3)
Requirement already satisfied: cython>=0.24.0 in /Users/keunwooc/opt/miniconda3/envs/dcunettorch/lib/python3.7/site-packages (from pyworld==0.2.8) (0.29.6)
Building wheels for collected packages: pyworld
  Building wheel for pyworld (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/keunwooc/opt/miniconda3/envs/dcunettorch/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y2/h6qxnmv11bsgxbqb_3w431s80000gn/T/pip-req-build-0wlbuvqw/setup.py'"'"'; __file__='"'"'/private/var/folders/y2/h6qxnmv11bsgxbqb_3w431s80000gn/T/pip-req-build-0wlbuvqw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/y2/h6qxnmv11bsgxbqb_3w431s80000gn/T/pip-wheel-n7zr8j_8 --python-tag cp37
       cwd: /private/var/folders/y2/h6qxnmv11bsgxbqb_3w431s80000gn/T/pip-req-build-0wlbuvqw/
  Complete output (31 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/pyworld
  copying pyworld/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/pyworld
  running build_ext
  cythoning pyworld/pyworld.pyx to pyworld/pyworld.cpp
  /Users/keunwooc/opt/miniconda3/envs/dcunettorch/lib/python3.7/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /private/var/folders/y2/h6qxnmv11bsgxbqb_3w431s80000gn/T/pip-req-build-0wlbuvqw/pyworld/pyworld.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'pyworld.pyworld' extension
  creating build/temp.macosx-10.7-x86_64-3.7
  creating build/temp.macosx-10.7-x86_64-3.7/pyworld
  creating build/temp.macosx-10.7-x86_64-3.7/lib
  creating build/temp.macosx-10.7-x86_64-3.7/lib/World
  creating build/temp.macosx-10.7-x86_64-3.7/lib/World/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/keunwooc/opt/miniconda3/envs/dcunettorch/include -arch x86_64 -I/Users/keunwooc/opt/miniconda3/envs/dcunettorch/include -arch x86_64 -Ilib/World/src -I/Users/keunwooc/opt/miniconda3/envs/dcunettorch/include/python3.7m -I/Users/keunwooc/opt/miniconda3/envs/dcunettorch/lib/python3.7/site-packages/numpy/core/include -c pyworld/pyworld.cpp -o build/temp.macosx-10.7-x86_64-3.7/pyworld/pyworld.o
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  In file included from pyworld/pyworld.cpp:607:
  In file included from /Users/keunwooc/opt/miniconda3/envs/dcunettorch/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /Users/keunwooc/opt/miniconda3/envs/dcunettorch/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
  In file included from /Users/keunwooc/opt/miniconda3/envs/dcunettorch/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:
  /Users/keunwooc/opt/miniconda3/envs/dcunettorch/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it by " \
   ^
  pyworld/pyworld.cpp:609:10: fatal error: 'ios' file not found
  #include "ios"
           ^~~~~
  2 warnings and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyworld
  Running setup.py clean for pyworld
Failed to build pyworld
Installing collected packages: pyworld
    Running setup.py install for pyworld ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/keunwooc/opt/miniconda3/envs/dcunettorch/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y2/h6qxnmv11bsgxbqb_3w431s80000gn/T/pip-req-build-0wlbuvqw/setup.py'"'"'; __file__='"'"'/private/var/folders/y2/h6qxnmv11bsgxbqb_3w431s80000gn/T/pip-req-build-0wlbuvqw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y2/h6qxnmv11bsgxbqb_3w431s80000gn/T/pip-record-hh6x1exb/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/y2/h6qxnmv11bsgxbqb_3w431s80000gn/T/pip-req-build-0wlbuvqw/
    Complete output (29 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/pyworld
    copying pyworld/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/pyworld
    running build_ext
    skipping 'pyworld/pyworld.cpp' Cython extension (up-to-date)
    building 'pyworld.pyworld' extension
    creating build/temp.macosx-10.7-x86_64-3.7
    creating build/temp.macosx-10.7-x86_64-3.7/pyworld
    creating build/temp.macosx-10.7-x86_64-3.7/lib
    creating build/temp.macosx-10.7-x86_64-3.7/lib/World
    creating build/temp.macosx-10.7-x86_64-3.7/lib/World/src
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/keunwooc/opt/miniconda3/envs/dcunettorch/include -arch x86_64 -I/Users/keunwooc/opt/miniconda3/envs/dcunettorch/include -arch x86_64 -Ilib/World/src -I/Users/keunwooc/opt/miniconda3/envs/dcunettorch/include/python3.7m -I/Users/keunwooc/opt/miniconda3/envs/dcunettorch/lib/python3.7/site-packages/numpy/core/include -c pyworld/pyworld.cpp -o build/temp.macosx-10.7-x86_64-3.7/pyworld/pyworld.o
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from pyworld/pyworld.cpp:607:
    In file included from /Users/keunwooc/opt/miniconda3/envs/dcunettorch/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /Users/keunwooc/opt/miniconda3/envs/dcunettorch/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /Users/keunwooc/opt/miniconda3/envs/dcunettorch/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:
    /Users/keunwooc/opt/miniconda3/envs/dcunettorch/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    pyworld/pyworld.cpp:609:10: fatal error: 'ios' file not found
    #include "ios"
             ^~~~~
    2 warnings and 1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/keunwooc/opt/miniconda3/envs/dcunettorch/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y2/h6qxnmv11bsgxbqb_3w431s80000gn/T/pip-req-build-0wlbuvqw/setup.py'"'"'; __file__='"'"'/private/var/folders/y2/h6qxnmv11bsgxbqb_3w431s80000gn/T/pip-req-build-0wlbuvqw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/y2/h6qxnmv11bsgxbqb_3w431s80000gn/T/pip-record-hh6x1exb/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```

**Comment by r9y9** [comment]
You might want to try:

```
MACOSX_DEPLOYMENT_TARGET=10.9 pip install .
```

**Comment by r9y9** [comment]
I guess the problem is the same as https://github.com/SeanNaren/warp-ctc/issues/129#issuecomment-502349652

**Comment by ZacheryGuan** [comment]
> You might want to try:
> 
> ```
> MACOSX_DEPLOYMENT_TARGET=10.9 pip install .
> ```

It works for me. MacOS 10.14, gcc 10.0.0, python 3.6.

**Comment by PatrickSLU** [comment]
hello i want to ask if anyone can help, i am running a code on google collab, i am using m1 mac
i am encountering

Building wheels for collected packages: pyworld
error: subprocess-exited-with-error

× Building wheel for pyworld (pyproject.toml) did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Building wheel for pyworld (pyproject.toml) ... error
ERROR: Failed building wheel for pyworld
Failed to build pyworld
ERROR: Could not build wheels for pyworld, which is required to install pyproject.toml-based projects

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
Requirement already satisfied: scipy==1.10.1 in /usr/local/lib/python3.10/dist-packages (1.10.1)
Requirement already satisfied: numpy<1.27.0,>=1.19.5 in /usr/local/lib/python3.10/dist-packages (from scipy==1.10.1) (1.23.5)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
Requirement already satisfied: SoundFile==0.12.1 in /usr/local/lib/python3.10/dist-packages (0.12.1)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.10/dist-packages (from SoundFile==0.12.1) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.0->SoundFile==0.12.1) (2.21)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
Collecting torch==1.13.1
Downloading https://download.pytorch.org/whl/cu116/torch-1.13.1%2Bcu116-cp310-cp310-linux_x86_64.whl (1977.9 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 GB 915.7 kB/s eta 0:00:00
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch==1.13.1) (4.7.1)
Installing collected packages: torch
Attempting uninstall: torch
Found existing installation: torch 2.0.1+cu118
Uninstalling torch-2.0.1+cu118:
Successfully uninstalled torch-2.0.1+cu118
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 1.13.1+cu116 which is incompatible.
torchdata 0.6.1 requires torch==2.0.1, but you have torch 1.13.1+cu116 which is incompatible.
torchtext 0.15.2 requires torch==2.0.1, but you have torch 1.13.1+cu116 which is incompatible.
torchvision 0.15.2+cu118 requires torch==2.0.1, but you have torch 1.13.1+cu116 which is incompatible.
Successfully installed torch-1.13.1+cu116

does anyone know how to resolve this?
