### ISSUE TITLE
Does not work in Anaconda

### ISSUE THREAD

**Issue by tats-u** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#12]
I found pyworld doesn't work for Python in Anaconda (https://www.continuum.io/downloads) in Ubuntu 17.04, presumably because the libstdc++ of Anaconda is of GCC 4.8 and too old for pyworld, which assumedly requires that of GCC 4.9 or later.  Python 2.7 and 3.6 says the same error message.

Example in Python 2.7:

```
$ conda create -n envname python=2.7 anaconda
$ source activate envname
$ pip install pyworld
$ python -c 'import pyworld'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/tatsu/anaconda3/envs/sprocket27/lib/python2.7/site-packages/pyworld/__init__.py", line 7, in <module>
    from .pyworld import *
ImportError: /home/tatsu/anaconda3/envs/sprocket27/lib/python2.7/site-packages/pyworld/pyworld.so: undefined symbol: __cxa_throw_bad_array_new_length
$ conda list | fgrep gcc
libgcc                    4.8.5                         2
```

**Comment by r9y9** [comment]
I tried the same commands except for adding `--no-cache-dir` to `pip install` and got no errors on ubuntu 16.04. During initializing the python environment, it seems libgcc 4.8.5-2 installed to me.

```
conda list | grep libgcc
libgcc                    4.8.5                         2  
```

```
ldd ~/anaconda3/envs/pyworld27/lib/python2.7/site-packages/pyworld/pyworld.so
        linux-vdso.so.1 =>  (0x00007ffe8b519000)
        libpython2.7.so.1.0 => /home/ryuichi/anaconda3/envs/pyworld27/lib/libpython2.7.so.1.0 (0x00007f0e346e9000)
        libstdc++.so.6 => /home/ryuichi/anaconda3/envs/pyworld27/lib/libstdc++.so.6 (0x00007f0e343d2000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0e34086000)
        libgcc_s.so.1 => /home/ryuichi/anaconda3/envs/pyworld27/lib/libgcc_s.so.1 (0x00007f0e33e70000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0e33c52000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0e33888000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0e33684000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f0e33480000)
        /lib64/ld-linux-x86-64.so.2 (0x0000562e5944b000)
```

In case if you are using old metadata, you can try  `conda update`. If it doesn't work, you may be linking against the (possibly system?) old libgcc. It would be useful to which version of `libgcc` you are linking against if you can paste the `ldd` output as above.

**Comment by tats-u** [comment]
I'm sorry, I didn't know how to identify the version of libstdc++.  I confirmed that is wrong that its version is of GCC 4.4 and correct 4.8.  I corrected the above message.

```
$ conda list | fgrep gcc
libgcc                    4.8.5                         2
```

**Comment by tats-u** [comment]
I recreate a virtual environment of Python 2.7 of Anaconda and installed pyworld by `pip` with the option `--no-cache-dir`, but I ran into the same error.

```
$ conda env remove -n envname
$ conda create -n sprocket27 python=2.7 envname
$ source activate envname
$ pip install --no-cache-dir pyworld
Collecting pyworld
  Downloading pyworld-0.2.1b0.tar.gz (70kB)
    100% |████████████████████████████████| 71kB 1.9MB/s
Requirement already satisfied: numpy in ./anaconda3/envs/envname/lib/python2.7/site-packages (from pyworld)
Installing collected packages: pyworld
  Running setup.py install for pyworld ... done
Successfully installed pyworld-0.2.1b0
$ python -c 'import pyworld'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/anaconda3/envs/envname/lib/python2.7/site-packages/pyworld/__init__.py", line 7, in <module>
    from .pyworld import *
ImportError: /home/user/anaconda3/envs/envname/lib/python2.7/site-packages/pyworld/pyworld.so: undefined symbol: __cxa_throw_bad_array_new_length
```

**Comment by r9y9** [comment]
I'm not sure if the issue is related to anaconda. What's the output of `ldd`? Does that show `pyworld.so` is being linked against libgcc/libstd++ shipped with anaconda, not system ones?

Possibly related: https://github.com/scikit-learn/scikit-learn/issues/7869, https://github.com/conda/conda/issues/3897.

If the issue is caused by version mismatch between gcc and libgcc (I'm not sure though), you may fix your proglem by

1. `conda update libgcc` to update libgcc4 to libgcc5, 
2. `conda uninstall libgcc` to force linking with system libgcc
3. `conda install gcc` and use it to compile `pyworld`

**Comment by tats-u** [comment]
After `conda upgrade --all anaconda -y` in the virtual and root environments, `python -c `import pyworld` does work without errors.  I'm sorry to bother you.
