### ISSUE TITLE
add parameters `frame shift` & `frame length `

### ISSUE THREAD

**Issue by lsq357** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#19]
How can I set `frame shift` & `frame length ` when use https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder/blob/4a7289e16f930a74c6c644f5df94a5094443343e/demo/demo.py#L64.
It only support `frame_period` parameters.
And `frame_period` represents  `frame shift` or `frame length`?

**Comment by JeremyCCHsu** [comment]
Currently, the original code of WORLD does not provide a `frame length` parameter to the users. To learn more from the author, please refer to https://github.com/mmorise/World/issues/51
