### ISSUE TITLE
Feature extraction: pyworld doesn't yield to same results as world/analysis (Merlin)

### ISSUE THREAD

**Issue by cveaux** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#25]
Hi, I was comparing the results of the feature extraction with pyworld and the ones I get from the analysis.cpp routine interfacing world library in Merlin (https://github.com/CSTR-Edinburgh/merlin/blob/master/tools/WORLD/test/analysis.cpp). I have used exactly the same settings (minf0 = 71.0, maxf0=800.0, q1=-0.15, allowed_range = 0.1, d4c_threshold=0.) but I get somewhat some different results and don't understand why.
Here's the experiment I made:
![demo_copy_synthesis](https://user-images.githubusercontent.com/22403532/37800682-9479193c-2e1b-11e8-8877-941e584249f5.png)

**Comment by r9y9** [comment]
Looks like wav samples are normalized to [-1, 1] from [-32768, 32767].  Can you try with unnormalized samples? As far as I remember WORLD uses unnormalized inputs.

**Comment by cveaux** [comment]
I tried with the unnormalised audio but I got the same results unfortunately.

![demo_copy_synthesis](https://user-images.githubusercontent.com/22403532/37808974-1cb96b20-2e45-11e8-8b0b-a40556c7b689.png)

**Comment by r9y9** [comment]
um, why do you use Merlin version of WORLD? It's apparently different from WORLD master and pyworld...

**Comment by cveaux** [comment]
I'm not tied to the Merlin version of WORLD, it was just a comparison point and because it does actually sound better. But I wanted a more pythonic and modular interface especially because it makes it easier to use a different F0 estimator input for cheaptrick.

**Comment by cveaux** [comment]
I'm not sure that the problem comes from the different version of WORLD, the differences are marginal and I also made a test where I replaced the source code of WORLD (in pyworld/lib) with the one used in Merlin, and rebuild and installed this modified pyworld on my machine but still get the difference in the results.

**Comment by r9y9** [comment]
I think the difference matters. FWIW, I did consistency check between Julia wrapper and WORLD (https://github.com/r9y9/WORLD.jl/blob/830c086ec8a7d03050c4506733241f72851af08b/test/consistency.jl) before and confirmed it's OK. You may need to be careful about numerical precision.

**Comment by cveaux** [comment]
Ok, thanks for the reply and the link. I think that the different kFloorF0 values used in the versions I was comparing could explained these results. Merlin's world version has kFloorF0 = 120 Hz instead of 71 Hz in the latest WORLD version.
