### ISSUE TITLE
Hop size vs frame size

### ISSUE THREAD

**Issue by Novak3** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#36]
I see that there is a way to adjust the frame size, with the frame_period argument to dio. 
Is there a way to independently change the hop size?  It seems like in PyWorld, the two are identical, whereas in STFT it is common for the frame size to be larger than the hop size as a way of increasing frequency resolution.  The hope is often 1/4 of the frame.

Is this possible in PyWorld?  

(I've never seen such a thing suggested for World in general.  Please pardon my ignorance if the World architecture just doesn't support this.)

**Comment by JeremyCCHsu** [comment]
There are 3 things that you are talking about:
1. `frame rate`: a.k.a. `frame shift` or `hop size`. Usually, `frame rate` <= `frame length`. The number of waveform samples that a frame (a.k.a. `window`) moves after computing the FFT.
2. `frame length`: the actual number of waveform samples that is taken into consideration.
3. `FFT length`: the size of the **zero-padded** frame. Note that `FFT length` >= `frame length`.

In STFT, all these 3 are adjustable. See, for example, scipy's [spectrogram](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.spectrogram.html). 

In WORLD vocoder, only 1 and 3 are adjustable; the reason that 2 is not adjustable is explained in the WORLD repo [here](https://github.com/mmorise/World/issues/51).

However, I'm actually not sure about what you mean by hop size and which parameter you want to adjust. Let me know whether this helps. 

Thanks.

**Comment by JeremyCCHsu** [comment]
closed due to inactivity.
