### ISSUE TITLE
Throws error on MacOS

### ISSUE THREAD

**Issue by Sasikanth3** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#37]
You cannot get it to compile on macOS because include files can't be found.

**Comment by Sasikanth3** [comment]
Add the below compile arguments to ext_modules in setup.py file
        extra_compile_args=['-std=c++11', '-v','-mmacosx-version-min=10.14'],

**Comment by felipeespic** [comment]
That didn't work for me in Mojave. I had to install Xcode Command Line Tools 9.4, and now is working :)
