### ISSUE TITLE
F0 with same length of audio file

### ISSUE THREAD

**Issue by bagustris** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#38]
Hi Jeremy, 

Thank you for the works making world accessible in python. I have a question: Is it possible to obtain the F0 contour with the length same as original audio file? For example, using `vaiueo2d.wav`, the original signal length is 17500 samples. By using `pw.dio` with default parameters (frame_period=5), we got 159 samples for 790 ms. I mean, how can I get the same length of F0 contour as an original audio file (aka F0 trajectories)? 

FYI, if I make the frame_period shorter (to get more length), the quality of F0 changing to be worse/rough.

**Comment by JeremyCCHsu** [comment]
Hi. As the sampling rate is 22050, a 5 ms frame period means 110 samples. This is why the resulting number of frames is 159 (=17500 / 110). I'm not sure why you meant by having an F0 contour with the same length of the input. You have to re-scale the time-axis yourself; that's what people usually do to have an "F0 contour". (So basically, we don't have an "F0-contour per sample.")

As for the phenomenon that shorter frame_period gets you worse F0. This is unexpected. Can you elaborate? I also suggest that you search the issues in the original [World repo](https://github.com/mmorise/World) and see if there's a hint. Thanks.

**Comment by bagustris** [comment]
Thank for the response.

I want to have the same exact sample with the original as I want to know/remove unvoiced parts. It is common in conference paper showing F0 trajectories plot. Thanks for your suggestion for re-scale, but I wonder If there is an argument for passing this value.

The following plot is made from `vaiueo.wav` with default frame_period and frame_period=5. Using small frame_period may lead to sharpening F0 as shown in the plot. However, I am expecting a similar result with the default frame period with length the same as the input. Finally, I found [amfm_decompy](https://github.com/bjbschmitt/AMFM_decompy) can do this.

![Figure_1](https://user-images.githubusercontent.com/3158361/55954853-c61cb580-5c9a-11e9-857c-ddc3edc1da3b.png)

**Comment by mrgloom** [comment]
I wonder why input `x.shape (17500,)` but reconstructed output is `y.shape (17529,)` in demo.py?
https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder/blob/master/demo/demo.py

Other data:
```
f0.shape (159,)
sp.shape (159, 513)
ap.shape (159, 513)
```

**Comment by JeremyCCHsu** [comment]
@mrgloom It is because that 159*110.25 = 17529.75 
The frame shift should be 110.25, not 110; I apologize if I confused you in my previous reply. 
I forget how they handle the decimal part, but you can ask in their [official repo](https://github.com/mmorise/World).

**Comment by JeremyCCHsu** [comment]
closed due to inactivity.
