### ISSUE TITLE
Memory errors in pyworld.synthesize()

### ISSUE THREAD

**Issue by QEDan** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#41]
I get segmentation faults when using non-default combinations of `frame_period` and `fft_size`. For example, the following script results in a segmentation fault:

> double free or corruption (!prev)
> Program received signal SIGABRT, Aborted.

```
import pyworld as pw
import numpy as np

frame_period = 5.0
fft_size = 64
fs = 16000
x = np.zeros((fs * 3))
f0, sp, ap = pw.wav2world(x, fs,
                          fft_size=fft_size,
                          frame_period=frame_period)
y = pw.synthesize(f0, sp, ap, fs, frame_period=frame_period)
```

I get the same problem whether using `np.zeros()`, real audio files, or random noise, so I don't think it's related to the input audio at all.

Replacing `fft_size` with `128` or larger tends to resolve the segmentation fault.

The following parameter combinations (with the code above) will result in an error of
> free(): invalid size
```
frame_period = 5.0
fft_size = 128
fs = 32000
```

The backtraces from gdb generally show the problems are occurring in the synthesize method of the c++ library. I am not sure whether the cause of the problem is in the python wrapper or in the c++ library, so please let me know if I should report these problems in that project.

Thank you for your help.

**Comment by JeremyCCHsu** [comment]
Replied in https://github.com/mmorise/World/issues/84
