### ISSUE TITLE
Could we have "f0, sp, ap -> spectrogram"?

### ISSUE THREAD

**Issue by sniperwrb** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#42]
The function pw.synthesize(f0, sp, ap) gives time-domain speech.
Sometimes I want it to synthesize an (amplitude) spectrogram.
Now I have to synthesize the speech, and then do STFT. I think it is a waste of time.
Is it possible to have something that converts (f0, sp, ap) to amplitude spectrogram?

**Comment by JeremyCCHsu** [comment]
You might need to redirect this to https://github.com/mmorise/World as this could be done in the wrapper end.

`sp` is actually a smoothed version of the spectrogram, but I'm not sure whether this is what you want. If you can address your question with more details, I can provide you with some suggestions.
