### ISSUE TITLE
`allowed_range` parameter in DIO does not work

### ISSUE THREAD

**Issue by LucasRr** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#45]
Hi,

I tried modifying the `allowed_range` parameter in DIO as:
```
f0, t = pw.dio(x, fs, allowed_range = 0.1)
```
with different values, but the result is always the same (even with `allowed_range = 0`).

**Comment by victor-shepardson** [comment]
I noticed this as well in the 0.2.8 release. appears to be fixed in master. I was able to get it working by installing from source as per the readme.

**Comment by LucasRr** [comment]
Yes same, installing from the repo fixed the problem, I forgot to close the issue.
