### ISSUE TITLE
How can I save the generated audio as a  int16 WAV

### ISSUE THREAD

**Issue by MeiGM** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#46]
The audio sequence generated by the vocoder is 64-bit floating point. When I want to save them as int16, they all return to zero. Is there any way to solve this problem?

**Comment by JeremyCCHsu** [comment]
The output format is handled by the audio I/O packages such as soundfile. You can also convert it before saving. See https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.wavfile.write.html for the range of int16.

**Comment by MeiGM** [comment]
Thank you for your reply.When I try to convert sequences to int16 with the following code, all sequence elements are zeroed, I can't solve this problem.
![TIM截图20191108100049](https://user-images.githubusercontent.com/43471923/68443394-b5232b00-020e-11ea-9a0c-e0ee00e229f0.png)

**Comment by JeremyCCHsu** [comment]
I guess your forgot to multiply your `wav` by `32767`.
`wav` arrays that were originally `float` usually have the value in the range of `[-1.0, 1.0]`, so without the the scaling that I described earlier, everything will be rounded to integer 0.

**Comment by MeiGM** [comment]
Thank you for your reply. I solved my problem and thank you again.
