### ISSUE TITLE
File "pyworld/pyworld.pyx", line 93, in pyworld.pyworld.dio ValueError: ndarray is not C-contiguous

### ISSUE THREAD

**Issue by ccl-private** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#48]
I tried the example code, and this error occurred.
![image](https://user-images.githubusercontent.com/36214675/83612814-83602000-a5b5-11ea-8c2a-c1829ffdf28e.png)

![image](https://user-images.githubusercontent.com/36214675/83612869-94109600-a5b5-11ea-8b1c-e319afbb3a0d.png)

**Comment by JeremyCCHsu** [comment]
Hi, may you provided us with your 
- system info (`lsb_release -a`)
- python version, 
- and how you installed it? (via pip or did you build it from source?)

Thanks

**Comment by ccl-private** [comment]
I finally solved it. I used "data = np.array(data, np.double)", and then problem solved.
