### ISSUE TITLE
How to turn AP into BAP?

### ISSUE THREAD

**Issue by ericwudayi** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#51]
As title, Does there exist a pyworld function to turn AP (513 dim) into BAP (5 dim)? Thank you very much!

**Comment by Lukelluke** [comment]
> As title, Does there exist a pyworld function to turn AP (513 dim) into BAP (5 dim)? Thank you very much!

hi, as  my little knowledge, i have never find that such function, but you can get .bap feature by Merlin toolkit.

**Comment by giridhar-pamisetty** [comment]
You can use the below function to do so.

bap = pw.code_aperiodicity(ap, fs)

The dimension of BAP depends on the sample rate (fs). Please note that the obtained BAP is in log scale.
