### ISSUE TITLE
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

### ISSUE THREAD

**Issue by turian** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#63]
I'm trying to 

```
python setup.py build
```

on [espnet](https://github.com/espnet/espnet).  If I pip3 install pyworld first, it's fine. If I don't, I get the following error from pyworld:

AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'

[This related fix](https://github.com/SciTools/cf-units/pull/153) might help.

**Comment by JeremyCCHsu** [comment]
Hi, may you explicate how to reproduce this issue? May you share your system configs, OS, Python version, device type, etc.? Ican't reproduce this issue on my side. I did `pip install espnet` and `pip install pyworld; pip install espnet` in two different Python 3.6 virtual environments (Ubuntu 18.04 on WSL) and both worked fine.
