### ISSUE TITLE
```numpy < 1.20``` breaks p3.10 compatibility

### ISSUE THREAD

**Issue by erogol** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#70]
Loosening numpy < 1.20 requirements can fix the problem if don't cause something else.
 
https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder/blob/cb69e0198be58e5bd68617062589dc131d56a6d7/pyproject.toml#L6

**Comment by RuilongXu** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zstanecic** [comment]
Hi,
I will provide a patch soon, so that pyworld can be build with python 3.10 and downwards, too.

**Comment by RuilongXu** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zstanecic** [comment]
This will get fixed for all platforms when my PR gets merged.
This relies on latest cython, numpy and scipy.
We no longer restrict ourselves to the particular package versions, but we choose the package chosen by pip automatically.

**Comment by JeremyCCHsu** [comment]
thx @zstanecic.
