### ISSUE TITLE
Update PyPi project

### ISSUE THREAD

**Issue by enkiid** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#76]
The pyworld project on PyPi needs to be updated with the latest version (0.3.1)

**Comment by kamo-naoyuki** [comment]
You haven't uploaded tgz file yet, but only uploaded whl. i.e. available for windows only now

https://pypi.org/project/pyworld/0.3.1/#files

**Comment by JeremyCCHsu** [comment]
I've just uploaded it manually. thx for reminding. I haven't figured out the mechanisms after Travis CI updated their service.
