### ISSUE TITLE
 pyworld/pyworld.cpp:724:10: fatal error: 'world/synthesis.h' file not found #include "world/synthesis.h"          ^~~~~~~~~~~~~~~~~~~ 1 warning and 1 error generated.

### ISSUE THREAD

**Issue by jinfagang** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#77]
****
pyworld/pyworld.cpp:724:10: fatal error: 'world/synthesis.h' file not found
#include "world/synthesis.h"
         ^~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.

**Comment by Laser-Cat** [comment]
You might be missing the world submodule, try 

git clone https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder.git --recursive

**Comment by JeremyCCHsu** [comment]
if you build from source, you need to fetch the C++ code using `git submodule update --init`
