### ISSUE TITLE
Usage of dash-separated 'description-file' deprecated in latest version

### ISSUE THREAD

**Issue by keviveks** [JeremyCCHsu/Python-Wrapper-for-World-Vocoder#81]
When try installing pyworld through the latest version of pip, throws an exception "Usage of dash-separated deprecated in the latest version"

Python 3.9.6
pip 22.3.1

<img width="1022" alt="Screenshot 2022-12-25 at 4 08 25 PM" src="https://user-images.githubusercontent.com/4748104/209464761-dd53c90a-b2e0-4f8d-afca-ef5bbfff532a.png">

**Comment by JeremyCCHsu** [comment]
#85
